"""
config.py
==============================================================================
Central configuration file for the CIFAKE project.

This module defines all paths, hyperparameters, and constants used across
the project (data loading, preprocessing, model architecture, training,
evaluation, prediction, and Grad-CAM). Keeping configuration in a single
place makes the project easy to extend and reproduce.

Based on:
    Bird, J.J. and Lotfi, A. (2024). "CIFAKE: Image Classification and
    Explainable Identification of AI-Generated Synthetic Images."
    IEEE Access, vol. 12, pp. 15642-15650.

Usage:
    from src import config
    print(config.IMAGE_SIZE)
"""

import os

# Native Windows CPU TensorFlow can hit oneDNN/MKL memory allocation failures
# with EfficientNet-sized batches. Disable oneDNN before TensorFlow imports;
# the app and training still run normally, just with the safer CPU kernels.
os.environ.setdefault("TF_ENABLE_ONEDNN_OPTS", "0")

# ------------------------------------------------------------------------
# BASE PROJECT PATHS
# ------------------------------------------------------------------------
# PROJECT_ROOT resolves to the top-level "project/" directory regardless
# of where this file is imported from.
SRC_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SRC_DIR)

# Dataset directory (expects CIFAKE dataset organised as below, see README):
#   train/REAL/*.jpg
#   train/FAKE/*.jpg
#   test/REAL/*.jpg
#   test/FAKE/*.jpg
DATASET_DIR = PROJECT_ROOT
TRAIN_DIR = os.path.join(DATASET_DIR, "train")
TEST_DIR = os.path.join(DATASET_DIR, "test")

# Saved model directory (checkpoints during training)
MODELS_DIR = os.path.join(PROJECT_ROOT, "models")

# Output directories (results generated by the pipeline)
OUTPUTS_DIR = os.path.join(PROJECT_ROOT, "outputs")
OUTPUT_MODELS_DIR = os.path.join(OUTPUTS_DIR, "models")
OUTPUT_GRAPHS_DIR = os.path.join(OUTPUTS_DIR, "graphs")
OUTPUT_PREDICTIONS_DIR = os.path.join(OUTPUTS_DIR, "predictions")
OUTPUT_GRADCAM_DIR = os.path.join(OUTPUTS_DIR, "gradcam")

# Logs directory (for file-based logging & TensorBoard)
LOGS_DIR = os.path.join(OUTPUTS_DIR, "logs")
TENSORBOARD_LOG_DIR = os.path.join(LOGS_DIR, "tensorboard")

# Ensure all output directories exist at import time.
for _dir in (
    MODELS_DIR,
    OUTPUTS_DIR,
    OUTPUT_MODELS_DIR,
    OUTPUT_GRAPHS_DIR,
    OUTPUT_PREDICTIONS_DIR,
    OUTPUT_GRADCAM_DIR,
    LOGS_DIR,
    TENSORBOARD_LOG_DIR,
):
    os.makedirs(_dir, exist_ok=True)

# ------------------------------------------------------------------------
# CLASS LABELS
# ------------------------------------------------------------------------
# Matches the CIFAKE paper convention: FAKE = 0, REAL = 1
CLASS_NAMES = ["FAKE", "REAL"]
CLASS_INDICES = {"FAKE": 0, "REAL": 1}
POSITIVE_CLASS = "REAL"

# ------------------------------------------------------------------------
# IMAGE / DATA PARAMETERS
# ------------------------------------------------------------------------
# EfficientNetB0 was pretrained on ImageNet at 224x224. The dataset loader
# and Flask prediction preprocessing both read this value, so changing it here
# preserves the existing app API while giving the transfer-learning backbone
# inputs closer to its pretraining distribution.
IMAGE_SIZE = (224, 224)
IMAGE_CHANNELS = 3
INPUT_SHAPE = (IMAGE_SIZE[0], IMAGE_SIZE[1], IMAGE_CHANNELS)

# Fraction of the training directory reserved for validation.
VALIDATION_SPLIT = 0.2

# Batch size for training / evaluation pipelines. EfficientNetB0 at 224x224
# is far larger than the old 32x32 CNN, so keep this conservative for CPU
# fallback and native Windows TensorFlow.
BATCH_SIZE = int(os.environ.get("CIFAKE_BATCH_SIZE", "8"))

# Optional batch limits make local CPU validation/training practical without
# changing the default full-dataset behavior.
MAX_TRAIN_BATCHES = int(os.environ.get("CIFAKE_MAX_TRAIN_BATCHES", "0"))
MAX_VAL_BATCHES = int(os.environ.get("CIFAKE_MAX_VAL_BATCHES", "0"))
MAX_TEST_BATCHES = int(os.environ.get("CIFAKE_MAX_TEST_BATCHES", "0"))

# Keep tf.data from buffering too many large 224x224 batches in RAM.
DATASET_NUM_PARALLEL_CALLS = 2
PREFETCH_BUFFER_SIZE = 1

# Shuffle buffer size for tf.data pipelines.
SHUFFLE_BUFFER_SIZE = 10000

# Random seed for reproducibility (data shuffling, weight init, etc.)
RANDOM_SEED = 1

# ------------------------------------------------------------------------
# DATA AUGMENTATION PARAMETERS
# ------------------------------------------------------------------------
AUGMENTATION_CONFIG = {
    "random_flip": "horizontal",
    "random_rotation": 0.08,      # fraction of 2*pi
    "random_zoom": 0.15,
    "random_translation": 0.08,
    "random_contrast": 0.15,
    "random_brightness": 0.12,
}

# ------------------------------------------------------------------------
# MODEL ARCHITECTURE
# ------------------------------------------------------------------------
MODEL_BACKBONE = "EfficientNetB0"
IMAGENET_WEIGHTS = "imagenet"
HEAD_DENSE_UNITS = 256
HEAD_DROPOUT_RATE = 0.4
FINE_TUNE_LAST_LAYERS = 40

# Legacy CNN settings are kept so older scripts importing these names do not
# break. The default training path now uses EfficientNet transfer learning.
CONV_FILTERS = [32, 32]        # number of filters per convolutional layer
CONV_KERNEL_SIZE = (3, 3)
POOL_SIZE = (2, 2)
DENSE_UNITS = [64]             # number of units per dense layer
DROPOUT_RATE = 0.3
USE_BATCH_NORM = True

# ------------------------------------------------------------------------
# TRAINING HYPERPARAMETERS
# ------------------------------------------------------------------------
EPOCHS = 50
PHASE1_EPOCHS = 20
PHASE2_EPOCHS = 30
LEARNING_RATE = 1e-3
FINE_TUNE_LEARNING_RATE = 1e-5
LOSS_FUNCTION = "binary_crossentropy"
OPTIMIZER_NAME = "adam"
METRICS = ["accuracy", "precision", "recall", "auc"]

# EarlyStopping
EARLY_STOPPING_PATIENCE = 8
EARLY_STOPPING_MONITOR = "val_loss"

# ReduceLROnPlateau
REDUCE_LR_PATIENCE = 4
REDUCE_LR_FACTOR = 0.5
REDUCE_LR_MIN_LR = 1e-6

# ModelCheckpoint
CHECKPOINT_MONITOR = "val_loss"
CHECKPOINT_FILENAME = "best_model.keras"
CHECKPOINT_PATH = os.path.join(OUTPUT_MODELS_DIR, CHECKPOINT_FILENAME)

# Final model save path (after training completes)
FINAL_MODEL_PATH = os.path.join(OUTPUT_MODELS_DIR, "cifake_final_model.keras")

# Training history (as JSON/CSV) for later inspection / plotting
HISTORY_CSV_PATH = os.path.join(OUTPUT_GRAPHS_DIR, "training_history.csv")

# ------------------------------------------------------------------------
# EVALUATION / PREDICTION
# ------------------------------------------------------------------------
CLASSIFICATION_THRESHOLD = 0.5  # sigmoid output rounding threshold

# ------------------------------------------------------------------------
# GRAD-CAM CONFIGURATION
# ------------------------------------------------------------------------
# Name of the top-level convolutional layer used by the existing Grad-CAM
# helper. model.py exposes this small projection after the EfficientNet
# feature map so Grad-CAM stays compatible with the existing implementation.
GRADCAM_LAST_CONV_LAYER = "gradcam_last_conv"
GRADCAM_ALPHA = 0.4  # heatmap overlay transparency

# ------------------------------------------------------------------------
# LOGGING
# ------------------------------------------------------------------------
LOG_LEVEL = "INFO"
LOG_FILE = os.path.join(LOGS_DIR, "cifake_project.log")
LOG_FORMAT = "%(asctime)s | %(levelname)-8s | %(name)s | %(message)s"
